// このファイルは tools\gen-blockdefs.js が作ります。直接なおさないでください。
// ブロックの「正」は ui\js\blocks.js です。そちらを直して、.\build.ps1 を走らせてください。
//
// blockdefs.cpp の中（namespace nashi::w2k）に取りこまれる断片です。
// 自分では名前空間を開きません。

// clang-format off
static const CategoryDef kCategories[] = {
    { "events", "イベント", "#ffbf00" },
    { "talk", "セリフ", "#ff6680" },
    { "looks", "見た目", "#9966ff" },
    { "control", "制御", "#ffab19" },
    { "variables", "変数", "#ff8c1a" },
    { "operators", "演算", "#59c059" },
    { "info", "情報", "#5cb1d6" },
};
static const int kCategoryCount = 7;

static const OptionDef kOptions[] = {
    { "どちらか", "-1" },
    { "さくら", "0" },
    { "うにゅう", "1" },
    { "どこか", "" },
    { "あたま", "Head" },
    { "かお", "Face" },
    { "むね", "Bust" },
    { "スカート", "Skirt" },
    { "て", "Hand" },
    { "さくら", "0" },
    { "うにゅう", "1" },
    { "改行する", "1" },
    { "改行しない", "0" },
    { "さくら", "0" },
    { "うにゅう", "1" },
    { "さくら", "0" },
    { "うにゅう", "1" },
    { "（答え）", "-1" },
    { "0番目の値", "0" },
    { "1番目の値", "1" },
    { "2番目の値", "2" },
    { "四捨五入", "round" },
    { "切り捨て", "floor" },
    { "切り上げ", "ceil" },
    { "絶対値に", "abs" },
    { "（答え）", "-1" },
    { "0番目の値", "0" },
    { "1番目の値", "1" },
    { "2番目の値", "2" },
    { "いまの時", "hour" },
    { "いまの分", "minute" },
    { "いまの秒", "second" },
    { "いまの年", "year" },
    { "いまの月", "month" },
    { "いまの日", "day" },
    { "いまの曜日(0=日)", "weekday" },
    { "いまの曜日(名前)", "weekdayname" },
    { "いまごろ(朝/昼/夕方/夜)", "daypart" },
    { "いまの季節", "season" },
    { "起動してからの秒数", "uptime" },
    { "起動してからの分数", "uptimemin" },
    { "起動した回数", "boots" },
    { "今回のトーク回数", "talks" },
    { "前に出したトーク", "lasttalk" },
    { "ゴースト名", "ghostname" },
    { "シェル名", "shellname" },
    { "話しかけてきた相手", "commfrom" },
    { "言われたこと", "commtext" },
    { "0番目", "0" },
    { "1番目", "1" },
    { "2番目", "2" },
    { "3番目", "3" },
    { "4番目", "4" },
    { "5番目", "5" },
};

static const ArgDef kArgs[] = {
    { "event", ArgKind::EventName, ArgMode::Text, false, "OnBoot", 0, 0 },
    { "who", ArgKind::Dropdown, ArgMode::Text, false, "-1", 0, 3 },
    { "area", ArgKind::AreaName, ArgMode::Text, false, "", 3, 6 },
    { "event", ArgKind::EventName, ArgMode::Text, false, "OnNadeNade", 0, 0 },
    { "from", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "contains", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "event", ArgKind::EventName, ArgMode::Text, false, "OnCommunicate", 0, 0 },
    { "event", ArgKind::EventName, ArgMode::Text, false, "OnSecondChange", 0, 0 },
    { "everySec", ArgKind::Input, ArgMode::Number, false, "5", 0, 0 },
    { "name", ArgKind::Input, ArgMode::Text, true, "トーク", 0, 0 },
    { "weight", ArgKind::Input, ArgMode::Number, false, "1", 0, 0 },
    { "group", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "name", ArgKind::Input, ArgMode::Text, true, "あたらしいトーク", 0, 0 },
    { "who", ArgKind::Dropdown, ArgMode::Text, false, "0", 9, 2 },
    { "text", ArgKind::Input, ArgMode::Text, true, "こんにちは。", 0, 0 },
    { "nl", ArgKind::Dropdown, ArgMode::Text, false, "1", 11, 2 },
    { "count", ArgKind::Input, ArgMode::Number, false, "1", 0, 0 },
    { "label", ArgKind::Input, ArgMode::Text, true, "うん", 0, 0 },
    { "target", ArgKind::FuncName, ArgMode::Text, false, "", 0, 0 },
    { "label", ArgKind::Input, ArgMode::Text, true, "ホームページ", 0, 0 },
    { "url", ArgKind::Input, ArgMode::Text, true, "https://", 0, 0 },
    { "who", ArgKind::Dropdown, ArgMode::Text, false, "0", 13, 2 },
    { "to", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "text", ArgKind::Input, ArgMode::Text, true, "こんにちは。", 0, 0 },
    { "text", ArgKind::Input, ArgMode::Text, true, "\\![raise,OnTest]", 0, 0 },
    { "who", ArgKind::Dropdown, ArgMode::Text, false, "0", 15, 2 },
    { "id", ArgKind::Input, ArgMode::Number, false, "0", 0, 0 },
    { "id", ArgKind::Input, ArgMode::Number, false, "2", 0, 0 },
    { "id", ArgKind::Input, ArgMode::Number, false, "0", 0, 0 },
    { "id", ArgKind::Input, ArgMode::Number, false, "0", 0, 0 },
    { "file", ArgKind::Input, ArgMode::Text, true, "sound.wav", 0, 0 },
    { "ms", ArgKind::Input, ArgMode::Number, false, "500", 0, 0 },
    { "cond", ArgKind::Input, ArgMode::Bool, false, "", 0, 0 },
    { "cond", ArgKind::Input, ArgMode::Bool, false, "", 0, 0 },
    { "count", ArgKind::Input, ArgMode::Number, false, "3", 0, 0 },
    { "cond", ArgKind::Input, ArgMode::Bool, false, "", 0, 0 },
    { "name", ArgKind::FuncName, ArgMode::Text, false, "", 0, 0 },
    { "group", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "sec", ArgKind::Input, ArgMode::Number, false, "180", 0, 0 },
    { "into", ArgKind::VarName, ArgMode::Text, false, "", 0, 0 },
    { "initial", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "sec", ArgKind::Input, ArgMode::Number, false, "30", 0, 0 },
    { "name", ArgKind::FuncName, ArgMode::Text, false, "", 0, 0 },
    { "event", ArgKind::Input, ArgMode::Text, true, "OnBoot", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "name", ArgKind::Input, ArgMode::Text, true, "random", 0, 0 },
    { "url", ArgKind::Input, ArgMode::Text, true, "https://", 0, 0 },
    { "file", ArgKind::Input, ArgMode::Text, true, "saori.dll", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "into", ArgKind::VarName, ArgMode::Text, false, "", 0, 0 },
    { "value", ArgKind::Dropdown, ArgMode::Text, false, "-1", 17, 4 },
    { "name", ArgKind::VarName, ArgMode::Text, false, "", 0, 0 },
    { "value", ArgKind::Input, ArgMode::Text, false, "0", 0, 0 },
    { "name", ArgKind::VarName, ArgMode::Text, false, "", 0, 0 },
    { "value", ArgKind::Input, ArgMode::Number, false, "1", 0, 0 },
    { "name", ArgKind::VarName, ArgMode::Text, false, "", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Number, false, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Number, false, "", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Number, false, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Number, false, "", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Number, false, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Number, false, "", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Number, false, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Number, false, "", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Number, false, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Number, false, "", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Text, false, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Text, false, "50", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Text, false, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Text, false, "50", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Text, false, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Text, false, "50", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Text, false, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Text, false, "50", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Bool, false, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Bool, false, "", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Bool, false, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Bool, false, "", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Bool, false, "", 0, 0 },
    { "min", ArgKind::Input, ArgMode::Number, false, "1", 0, 0 },
    { "max", ArgKind::Input, ArgMode::Number, false, "10", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Number, false, "50", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Text, true, "こんにちは", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Text, true, "さん", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Number, false, "", 0, 0 },
    { "op", ArgKind::Dropdown, ArgMode::Text, false, "round", 21, 4 },
    { "file", ArgKind::Input, ArgMode::Text, true, "saori.dll", 0, 0 },
    { "a", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "b", ArgKind::Input, ArgMode::Text, true, "", 0, 0 },
    { "value", ArgKind::Dropdown, ArgMode::Text, false, "-1", 25, 4 },
    { "key", ArgKind::Dropdown, ArgMode::Text, false, "hour", 29, 19 },
    { "index", ArgKind::Dropdown, ArgMode::Text, false, "0", 48, 6 },
};

static const PartDef kParts[] = {
    { true, "event" },
    { true, "who" },
    { false, " の " },
    { true, "area" },
    { false, " が " },
    { true, "event" },
    { true, "from" },
    { false, " に " },
    { true, "contains" },
    { false, " と " },
    { true, "event" },
    { true, "event" },
    { false, " " },
    { true, "everySec" },
    { false, " 秒ごと" },
    { false, "ランダムトーク「" },
    { true, "name" },
    { false, "」 えらばれやすさ " },
    { true, "weight" },
    { false, " まとまり " },
    { true, "group" },
    { false, "「" },
    { true, "name" },
    { false, "」がよばれたとき" },
    { true, "who" },
    { false, " が " },
    { true, "text" },
    { false, " と話す " },
    { true, "nl" },
    { true, "count" },
    { false, " 回 改行する" },
    { false, "クリックされるまで待つ" },
    { false, "バルーンの文字を消す" },
    { false, "選択肢「" },
    { true, "label" },
    { false, "」→ " },
    { true, "target" },
    { false, " を出す" },
    { false, "リンク「" },
    { true, "label" },
    { false, "」→ " },
    { true, "url" },
    { false, " を出す" },
    { true, "who" },
    { false, " が " },
    { true, "to" },
    { false, " に " },
    { true, "text" },
    { false, " と話しかける" },
    { false, "さくらスクリプト " },
    { true, "text" },
    { false, " をそのまま出す" },
    { true, "who" },
    { false, " の表情を " },
    { true, "id" },
    { false, " 番にする" },
    { false, "これから " },
    { true, "id" },
    { false, " 番のキャラが話す" },
    { false, "うごき " },
    { true, "id" },
    { false, " を再生する" },
    { false, "バルーンを " },
    { true, "id" },
    { false, " 番にする" },
    { false, "音 " },
    { true, "file" },
    { false, " を鳴らす" },
    { true, "ms" },
    { false, " ミリ秒待つ" },
    { false, "もし " },
    { true, "cond" },
    { false, " なら" },
    { false, "もし " },
    { true, "cond" },
    { false, " なら" },
    { true, "count" },
    { false, " 回くりかえす" },
    { true, "cond" },
    { false, " の間くりかえす" },
    { false, "つぎのどれかをランダムに" },
    { true, "name" },
    { false, " をよぶ" },
    { true, "group" },
    { false, " のトークをどれかよぶ" },
    { false, "ランダムトークの間隔を " },
    { true, "sec" },
    { false, " 秒にする" },
    { false, "たずねて、答えを " },
    { true, "into" },
    { false, " に入れる（はじめから " },
    { true, "initial" },
    { false, " と書いておく）" },
    { true, "sec" },
    { false, " 秒後に " },
    { true, "name" },
    { false, " をよぶ" },
    { false, "イベント " },
    { true, "event" },
    { false, " を自分で起こす（情報 " },
    { true, "a" },
    { false, " を付ける）" },
    { true, "name" },
    { false, " に交代する" },
    { true, "url" },
    { false, " をブラウザで開く" },
    { true, "file" },
    { false, " を " },
    { true, "a" },
    { false, " " },
    { true, "b" },
    { false, " でよぶ（答えを待たずに " },
    { true, "into" },
    { false, " に入れる）" },
    { true, "value" },
    { false, "ネットワーク更新をする" },
    { false, "ここでトークをおわる" },
    { false, "ゴーストを終了する" },
    { true, "name" },
    { false, " を " },
    { true, "value" },
    { false, " にする" },
    { true, "name" },
    { false, " を " },
    { true, "value" },
    { false, " ずつ変える" },
    { true, "name" },
    { true, "a" },
    { false, " ＋ " },
    { true, "b" },
    { true, "a" },
    { false, " − " },
    { true, "b" },
    { true, "a" },
    { false, " × " },
    { true, "b" },
    { true, "a" },
    { false, " ÷ " },
    { true, "b" },
    { true, "a" },
    { false, " のあまり " },
    { true, "b" },
    { true, "a" },
    { false, " ＜ " },
    { true, "b" },
    { true, "a" },
    { false, " ＝ " },
    { true, "b" },
    { true, "a" },
    { false, " ＞ " },
    { true, "b" },
    { true, "a" },
    { false, " ≠ " },
    { true, "b" },
    { true, "a" },
    { false, " かつ " },
    { true, "b" },
    { true, "a" },
    { false, " または " },
    { true, "b" },
    { true, "a" },
    { false, " ではない" },
    { true, "min" },
    { false, " から " },
    { true, "max" },
    { false, " までのランダムな数" },
    { true, "a" },
    { false, " ％のかくりつ" },
    { true, "a" },
    { false, " と " },
    { true, "b" },
    { false, " をつなげる" },
    { true, "a" },
    { false, " に " },
    { true, "b" },
    { false, " がふくまれる" },
    { true, "a" },
    { false, " の文字数" },
    { true, "a" },
    { false, " を " },
    { true, "op" },
    { true, "file" },
    { false, " を " },
    { true, "a" },
    { false, " " },
    { true, "b" },
    { false, " でよんだ答え " },
    { true, "value" },
    { true, "key" },
    { false, "イベントの情報 " },
    { true, "index" },
};

static const SubDef kSubs[] = {
    { "then", "" },
    { "then", "" },
    { "else", "そうでなければ" },
    { "body", "" },
    { "body", "" },
};

static const FixedDef kFixed[] = {
    { "op", "+" },
    { "op", "-" },
    { "op", "*" },
    { "op", "/" },
    { "op", "%" },
    { "op", "<" },
    { "op", "=" },
    { "op", ">" },
    { "op", "!=" },
    { "op", "and" },
    { "op", "or" },
};

static const BlockDef kBlocks[] = {
    { "@event", "@event", "events", Shape::Hat, "event", true, "", 0, 1, 0, 1, 0, 0, 0, 0 },
    { "@event.touch", "@event", "events", Shape::Hat, "event", true, "", 1, 3, 1, 5, 0, 0, 0, 0 },
    { "@event.comm", "@event", "events", Shape::Hat, "event", true, "", 4, 3, 6, 5, 0, 0, 0, 0 },
    { "@event.every", "@event", "events", Shape::Hat, "event", true, "", 7, 2, 11, 4, 0, 0, 0, 0 },
    { "@talk", "@talk", "events", Shape::Hat, "talk", true, "", 9, 3, 15, 6, 0, 0, 0, 0 },
    { "@function", "@function", "events", Shape::Hat, "function", true, "", 12, 1, 21, 3, 0, 0, 0, 0 },
    { "say", "say", "talk", Shape::Stack, "", false, "", 13, 3, 24, 5, 0, 0, 0, 0 },
    { "newline", "newline", "talk", Shape::Stack, "", false, "", 16, 1, 29, 2, 0, 0, 0, 0 },
    { "click_wait", "click_wait", "talk", Shape::Stack, "", false, "", 0, 0, 31, 1, 0, 0, 0, 0 },
    { "clear", "clear", "talk", Shape::Stack, "", false, "", 0, 0, 32, 1, 0, 0, 0, 0 },
    { "choice", "choice", "talk", Shape::Stack, "", false, "", 17, 2, 33, 5, 0, 0, 0, 0 },
    { "link", "link", "talk", Shape::Stack, "", false, "", 19, 2, 38, 5, 0, 0, 0, 0 },
    { "communicate", "communicate", "talk", Shape::Stack, "", false, "", 21, 3, 43, 6, 0, 0, 0, 0 },
    { "raw", "raw", "talk", Shape::Stack, "", false, "", 24, 1, 49, 3, 0, 0, 0, 0 },
    { "surface", "surface", "looks", Shape::Stack, "", false, "", 25, 2, 52, 4, 0, 0, 0, 0 },
    { "chara", "chara", "looks", Shape::Stack, "", false, "", 27, 1, 56, 3, 0, 0, 0, 0 },
    { "anim", "anim", "looks", Shape::Stack, "", false, "", 28, 1, 59, 3, 0, 0, 0, 0 },
    { "balloon", "balloon", "looks", Shape::Stack, "", false, "", 29, 1, 62, 3, 0, 0, 0, 0 },
    { "sound", "sound", "looks", Shape::Stack, "", false, "", 30, 1, 65, 3, 0, 0, 0, 0 },
    { "wait", "wait", "control", Shape::Stack, "", false, "", 31, 1, 68, 2, 0, 0, 0, 0 },
    { "if", "if", "control", Shape::CBlock, "", false, "", 32, 1, 70, 3, 0, 1, 0, 0 },
    { "if_else", "if_else", "control", Shape::CBlock, "", false, "", 33, 1, 73, 3, 1, 2, 0, 0 },
    { "repeat", "repeat", "control", Shape::CBlock, "", false, "", 34, 1, 76, 2, 3, 1, 0, 0 },
    { "while", "while", "control", Shape::CBlock, "", false, "", 35, 1, 78, 2, 4, 1, 0, 0 },
    { "random_one", "random_one", "control", Shape::CBlock, "", false, "branches", 0, 0, 80, 1, 0, 0, 0, 0 },
    { "call", "call", "control", Shape::Stack, "", false, "", 36, 1, 81, 2, 0, 0, 0, 0 },
    { "call_group", "call_group", "control", Shape::Stack, "", false, "", 37, 1, 83, 2, 0, 0, 0, 0 },
    { "talk_interval", "talk_interval", "control", Shape::Stack, "", false, "", 38, 1, 85, 3, 0, 0, 0, 0 },
    { "ask", "ask", "control", Shape::Stack, "", false, "", 39, 2, 88, 5, 0, 0, 0, 0 },
    { "later", "later", "control", Shape::Stack, "", false, "", 41, 2, 93, 4, 0, 0, 0, 0 },
    { "raise", "raise", "control", Shape::Stack, "", false, "", 43, 2, 97, 5, 0, 0, 0, 0 },
    { "change_ghost", "change_ghost", "control", Shape::Cap, "", false, "", 45, 1, 102, 2, 0, 0, 0, 0 },
    { "open_browser", "open_browser", "control", Shape::Stack, "", false, "", 46, 1, 104, 2, 0, 0, 0, 0 },
    { "saori_call", "saori_call", "control", Shape::Stack, "", false, "", 47, 5, 106, 9, 0, 0, 0, 0 },
    { "update", "update", "control", Shape::Stack, "", false, "", 0, 0, 115, 1, 0, 0, 0, 0 },
    { "end", "end", "control", Shape::Cap, "", false, "", 0, 0, 116, 1, 0, 0, 0, 0 },
    { "close", "close", "control", Shape::Cap, "", false, "", 0, 0, 117, 1, 0, 0, 0, 0 },
    { "set", "set", "variables", Shape::Stack, "", false, "", 52, 2, 118, 4, 0, 0, 0, 0 },
    { "change", "change", "variables", Shape::Stack, "", false, "", 54, 2, 122, 4, 0, 0, 0, 0 },
    { "var", "var", "variables", Shape::Reporter, "", false, "", 56, 1, 126, 1, 0, 0, 0, 0 },
    { "arith#+", "arith", "operators", Shape::Reporter, "", false, "", 57, 2, 127, 3, 0, 0, 0, 1 },
    { "arith#-", "arith", "operators", Shape::Reporter, "", false, "", 59, 2, 130, 3, 0, 0, 1, 1 },
    { "arith#*", "arith", "operators", Shape::Reporter, "", false, "", 61, 2, 133, 3, 0, 0, 2, 1 },
    { "arith#/", "arith", "operators", Shape::Reporter, "", false, "", 63, 2, 136, 3, 0, 0, 3, 1 },
    { "arith#%", "arith", "operators", Shape::Reporter, "", false, "", 65, 2, 139, 3, 0, 0, 4, 1 },
    { "compare#<", "compare", "operators", Shape::Boolean, "", false, "", 67, 2, 142, 3, 0, 0, 5, 1 },
    { "compare#=", "compare", "operators", Shape::Boolean, "", false, "", 69, 2, 145, 3, 0, 0, 6, 1 },
    { "compare#>", "compare", "operators", Shape::Boolean, "", false, "", 71, 2, 148, 3, 0, 0, 7, 1 },
    { "compare#!=", "compare", "operators", Shape::Boolean, "", false, "", 73, 2, 151, 3, 0, 0, 8, 1 },
    { "logic#and", "logic", "operators", Shape::Boolean, "", false, "", 75, 2, 154, 3, 0, 0, 9, 1 },
    { "logic#or", "logic", "operators", Shape::Boolean, "", false, "", 77, 2, 157, 3, 0, 0, 10, 1 },
    { "not", "not", "operators", Shape::Boolean, "", false, "", 79, 1, 160, 2, 0, 0, 0, 0 },
    { "random", "random", "operators", Shape::Reporter, "", false, "", 80, 2, 162, 4, 0, 0, 0, 0 },
    { "chance", "chance", "operators", Shape::Boolean, "", false, "", 82, 1, 166, 2, 0, 0, 0, 0 },
    { "join", "join", "operators", Shape::Reporter, "", false, "", 83, 2, 168, 4, 0, 0, 0, 0 },
    { "contains", "contains", "operators", Shape::Boolean, "", false, "", 85, 2, 172, 4, 0, 0, 0, 0 },
    { "length", "length", "operators", Shape::Reporter, "", false, "", 87, 1, 176, 2, 0, 0, 0, 0 },
    { "round", "round", "operators", Shape::Reporter, "", false, "", 88, 2, 178, 3, 0, 0, 0, 0 },
    { "saori", "saori", "operators", Shape::Reporter, "", false, "", 90, 4, 181, 7, 0, 0, 0, 0 },
    { "sys", "sys", "info", Shape::Reporter, "", false, "", 94, 1, 188, 1, 0, 0, 0, 0 },
    { "ref", "ref", "info", Shape::Reporter, "", false, "", 95, 1, 189, 2, 0, 0, 0, 0 },
};
static const int kBlockCount = 61;

// パレットに出す順。"@vars" は「いまある変数」に置きかわる目じるしです。
static const PaletteRow kPalette[] = {
    { "events", "@event" },
    { "events", "@event.touch" },
    { "events", "@event.every" },
    { "events", "@event.comm" },
    { "events", "@talk" },
    { "events", "@function" },
    { "talk", "say" },
    { "talk", "newline" },
    { "talk", "click_wait" },
    { "talk", "clear" },
    { "talk", "choice" },
    { "talk", "link" },
    { "talk", "communicate" },
    { "talk", "raw" },
    { "looks", "surface" },
    { "looks", "chara" },
    { "looks", "anim" },
    { "looks", "balloon" },
    { "looks", "sound" },
    { "control", "wait" },
    { "control", "if" },
    { "control", "if_else" },
    { "control", "repeat" },
    { "control", "while" },
    { "control", "random_one" },
    { "control", "call" },
    { "control", "call_group" },
    { "control", "talk_interval" },
    { "control", "ask" },
    { "control", "later" },
    { "control", "raise" },
    { "control", "update" },
    { "control", "saori_call" },
    { "control", "open_browser" },
    { "control", "end" },
    { "control", "close" },
    { "control", "change_ghost" },
    { "variables", "@vars" },
    { "variables", "set" },
    { "variables", "change" },
    { "operators", "arith#+" },
    { "operators", "arith#-" },
    { "operators", "arith#*" },
    { "operators", "arith#/" },
    { "operators", "arith#%" },
    { "operators", "compare#<" },
    { "operators", "compare#=" },
    { "operators", "compare#>" },
    { "operators", "compare#!=" },
    { "operators", "logic#and" },
    { "operators", "logic#or" },
    { "operators", "not" },
    { "operators", "random" },
    { "operators", "chance" },
    { "operators", "join" },
    { "operators", "contains" },
    { "operators", "length" },
    { "operators", "round" },
    { "operators", "saori" },
    { "info", "sys" },
    { "info", "ref" },
};
static const int kPaletteCount = 61;

// clang-format on
